### ISSUE TITLE
/lfs3/ to /lfs4 transition

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#412]
---

Author Name: **jeffrey.a.hamilton** (jeffrey.a.hamilton)
Original Redmine Issue: 78418, https://vlab.ncep.noaa.gov/redmine/issues/78418
Original Date: 2020-05-11
Original Assignee: jeffrey.a.hamilton

---

Move all amb-verif work from /lfs3 to /lfs4. /lfs3 to be decommissioned on June 30, 2020.

**Comment by bonnystrong** [comment]
This appears to be completed, so I'm closing it.
