### ISSUE TITLE
Correct Precip Analysis in ensemble verification and backfill

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#419]
---

Author Name: **jeffrey.a.hamilton** (jeffrey.a.hamilton)
Original Redmine Issue: 79115, https://vlab.ncep.noaa.gov/redmine/issues/79115
Original Date: 2020-05-29
Original Assignee: jeffrey.a.hamilton

---

The StageIV analysis that we use in ensemble precipitation verification has always been flawed when only comparing against our internally produced probabilities. This was due to use being unable to produce analysis files with the same Gaussian smoothing of maximum values within a neighborhood to match the same methodology used in the creation of the forecast probabilities themselves. Thanks to MET 9.0.1, this is now possible. Develop a workflow that does this and backfill all precip verification back to Oct 2019.

**Comment by bonnystrong** [comment]
Is this completed?

**Comment by JeffHamiltonNOAA** [comment]
Yes, this has been completed
