### ISSUE TITLE
Investigate compiling bufr for Bill's prepbufr code

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/VxLegacyIngest#472]
We want to be able to compile the bufr library by ourselves. We need to:

- [x] track down the source code (on Jet)
- [x] estimate how long it will take to compile it ourselves
- [x] document how to compile the library on Jet
- [x] Consider checking-in a script/cmake/makefiles that will compile libbufr for Bill's code.
- [x] test the newly built library with Bill's code

**Comment by bonnystrong** [comment]
Is this C code or Fortran?

**Comment by ian-noaa** [comment]
Ming believes this is not related to the GSI libraries and instead can be used directly from NOAA's [HPC-stack project](https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations). It looks like HPC-stack uses the [NCEPLIBS-bufr](https://github.com/NOAA-EMC/NCEPLIBS-bufr/) repo. Bill was finding that `/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/bufr/11.4.0/lib/libbufr_d_DA.a` worked for his code. This was bufr v11.4.0, built on Jet with the intel-18.0.5.274 compiler. This appears to be an older version of bufr and an older compiler so it may make sense to tests against a newer compiler (e.g. `intel/2022.1.2`) and a newer version of bufr. (i.e. v 11.7.0)

Bill found that the `libbufr_d_DA.a` library was the only one that worked with his code. The `d` signifies that the code uses 4 byte integers and 8 byte reals, and the `_DA` signifies that the code allows dynamic allocation. The v11.7.0 bufr equivalent would be `/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-2022.1.2/bufr/11.7.0/lib64/libbufr_d.a` as all of the bufr libs now use dynamic allocation.

I'll attempt to directly build libbufr from the NOAA_EMC/NCEPLIBS-bufr source code on Jet here today.

@bonnystrong - `libbufr` is written in Fortran.

**Comment by ian-noaa** [comment]
Steps I've taken:

Load the HPC modules according to their docs and the system you're on. The below instructions are for Jet. See: https://github.com/NOAA-EMC/hpc-stack/wiki/Official-Installations

```console
module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
# Load a recent version of the HPC stack
module load hpc/1.2.0
# Load a recent compiler
module load intel/2022.1.2
# Load a recent version of cmake
module load cmake/3.20.1
# checkout code at the needed tag, configure and build
git clone --branch bufr_v11.7.0 https://github.com/NOAA-EMC/NCEPLIBS-bufr.git
mkdir bufr-{build,install}
cd bufr-build
# Configure the build - you'll need to update the path
cmake -DCMAKE_INSTALL_REFIX=/home/path/to/bufr-install ../NCEPLIBS-bufr/
make -j4
ctest
make DESTDIR=/home/path/to/bufr-install install
```

And there should be a libbufr located at `/home/path/to/bufr-install/usr/local/lib64/libbufr_d.a`. It'd be good to test a library built like this with Bill's code to make sure that everything works as anticipated. We could also make this part of his build process.

**Comment by ian-noaa** [comment]
@JeffHamiltonNOAA - I believe I have a `libbufr` library built that will work with Bill's code. Do you know how to compile and test the prepbufr raob code on Jet or should we wait for Bill to do that?

Additionally - would adding the instructions above to the README for compiling and testing the prepbufr raob code be sufficient? Or should we try to incorporate this into the prepbufr code's build process somehow? At the moment, I believe the prepbufr raob code relies on a libbufr provided by EMC's HPC-stack team which seems reasonably supported. The only thing we might want to change would be to rely on a more modern version of libbufr.

**Comment by ian-noaa** [comment]
After talking with @JeffHamiltonNOAA - It looks like Bill compiles the prepbufr executable from `/whome/amb-verif/prepbufr_raob/compile`. The Makefile appears to be valid so `make prepbufr2txt_B` should work. However, cmake is also present and may be building some of the underlying libraries. I'll need to do a bit more digging to figure out where to inject the bufr library. 

Jeff did confirm that the above steps should be safe to do from the `amb-verif` roll account so I can go ahead and start messing with things.

**Comment by ian-noaa** [comment]
It appears this all is invoked from the cron like so:

```cron
# RAOBs from prepBUFR
10 7,19 * * *      $HOME/sb2.tcsh  pb_RAOBS $HOME/prepbufr_raob/do_prepbufr_raobs.pl   > /dev/null
10 8,20 * * *      $HOME/sb2.tcsh  persis_pb $HOME/prepbufr_raob/gen_persis.pl -1 0 > /dev/null
30 0-9,11-23 * * * $HOME/sb2.tcsh  RAP_OPS_iso_pb $HOME/prepbufr_raob/agen_raob_sites.pl RAP_OPS_iso -5 0  > /dev/null
30 0-9,11-23 * * * $HOME/sb2.tcsh  RAP_OPS_130_pb $HOME/prepbufr_raob/agen_raob_sites.pl RAP_OPS_130 -5 0  > /dev/null
32 0-9,11-23 * * * $HOME/sb2.tcsh  RAP_OPS_iso_130_pb $HOME/prepbufr_raob/agen_raob_sites.pl isoRRrapx -5 0  > /dev/null
33 0-9,11-23 * * * $HOME/sb2.tcsh  RAP_OPS_iso_242_pb $HOME/prepbufr_raob/agen_raob_sites.pl RAP_OPS_iso_242 -5 0  > /dev/null
54 0-9,11-23 * * * $HOME/sb2.tcsh  RTMA_3D_GSD_pb $HOME/prepbufr_raob/agen_raob_sites.pl RTMA_3D_GSD -5 0  > /dev/null
33 0-9,11-23 * * * $HOME/sb2.tcsh  HRRR_OPS_pb $HOME/prepbufr_raob/agen_raob_sites.pl HRRR_OPS -5 0  > /dev/null
33 0-9,11-23 * * * $HOME/sb2.tcsh  HRRR_AK_OPS_pb $HOME/prepbufr_raob/agen_raob_sites.pl HRRR_AK_OPS -5 0  > /dev/null
33 0-9,11-23 * * * $HOME/sb2.tcsh  HRRR_OPS_iso_pb $HOME/prepbufr_raob/agen_raob_sites.pl HRRR_OPS_iso -5 0  > /dev/null
33 0-9,11-23 * * * $HOME/sb2.tcsh  HRRR_AK_OPS_iso_pb $HOME/prepbufr_raob/agen_raob_sites.pl HRRR_AK_OPS_iso -5 0  > /dev/null
34 0-9,11-23 * * * $HOME/sb2.tcsh  GFS_pb $HOME/prepbufr_raob/agen_raob_sites.pl GFS -12 0  > /dev/null
40 0-9,11-23 * * * $HOME/sb2.tcsh  L128_pb $HOME/prepbufr_raob/agen_raob_sites.pl rt_ccpp_gsd_L128 -28 0  > /dev/null
44 0-9,11-23 * * * $HOME/sb2.tcsh  RRFS_NA_3km_dev1_HRRR_iso_pb $HOME/prepbufr_raob/agen_raob_sites.pl RRFS_NA_3km_dev1_HRRR_iso -12 0  > /dev/null
48 0-9,11-23 * * * $HOME/sb2.tcsh  RRFS_NA_3km_dev1_AK_iso_pb $HOME/prepbufr_raob/agen_raob_sites.pl RRFS_NA_3km_dev1_AK_iso -12 0  > /dev/null
```

Where `sb2.tcsh` is a shell script that submits slurm jobs:
```shell
#!/bin/tcsh

echo `dirname $2`
cd `dirname $2`
source ${HOME}/.cshrc
source ${HOME}/.cshrc

echo "sbatch -J ${HOST}_$1 $2 $3 $4 $5 $6 $7 $8 $9"
/apps/slurm/default/bin/sbatch -J ${HOST}_$1 $2 $3 $4 $5 $6 $7 $8 $9
exit;
```

`sbatch -J` consumes the first variable passed as the job name. So, we're primarily invoking the prepBUFR RAOB code through `do_prepbufr_raobs.pl`, `gen_persis.pl`, and `agen_raob_sites.pl`

**Comment by ian-noaa** [comment]
We have a bufr library for Bill to test at: `/lfs4/BMC/amb-verif/mcginnis/bufr-install/lib64/libbufr_d.a`

I could hook it into the Makefile above but it'd be best to confirm with him that that's the correct location as he'll need to check the output anyways.

**Comment by ian-noaa** [comment]
Bill had a chance to test the new library and gave the following update:

> I compared results from your library /`lfs4/BMC/amb-verif/mcginnis/bufr-install/lib64/libbufr_d.a` with the library I had been using (`/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/bufr/11.4.0/lib/libbufr_d_DA.a`). 
> 
> Out of 73000 lines in the output files `conv_type0120_202208220000.txt` and `conv_type0120_202208220000.old.txt`, only 9 lines differed, and then only by round-off error in the height, and in one case the temperature. I checked for an additional period and got similar results. I think these differences are negligible.
> 
> I did have to use gfortran, rather than ifort, for your library to work. And I had to eliminate the compiler flags I'd been using with ifort: `ifort  -g -traceback -ftz -O3 -no-wrap-margin`
