### ISSUE TITLE
Define methods for managing GitHub repos on HPC systems

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#474]
During the process of adding the prepbufr raob verification code to GitHub, issues arose as to the best way to handle the code and deploy for real time runs. Discuss with team members and come up with a strategy for development and management moving forward.

**Comment by JeffHamiltonNOAA** [comment]
Expanding the scope of this work to include retrospective scripts on Jet and Hera. The amount of directory structure and naming differences between various RRFS retros needs to be tracked in order to bring some sanity to this

**Comment by ian-noaa** [comment]
FYI - I opened a trial PR (https://github.com/NOAA-GSL/VxLegacyIngest/pull/498) to see what it would look like if we removed the binaries and temporary files I included in the [`.gitignore`](https://github.com/NOAA-GSL/VxLegacyIngest/blob/main/.gitignore) file. It's a large number of files. (~560) I feel okay about removing the vi/vim temp files. I'm a bit more concerned about removing the binaries - I think it'd be good to remove them. However, I'm not sure we know how to recreate them so I don't want to get rid of them if that's the case.

**Comment by JeffHamiltonNOAA** [comment]
This is happening as part of the role account renaming. Will update this issue once the naming is complete

**Comment by JeffHamiltonNOAA** [comment]
I have a script ready for crude "deploy/save" options to a checked out branch from the VxLegacyIngest repo, "accountRename". I'm waiting for Jet to be a bit more stable before officially turning the weekly save, commit, and push on, hopefully later this week

**Comment by JeffHamiltonNOAA** [comment]
I have the repository updated for both Hera and Jet code bases. I'm working on a script that will automate pushing to the repo, but am fighting some permission issues on Hera at the moment. In the meantime, users can push/pull from the verirication repo on the two machines here (after the changes that have been made are copied over from the role.amb-verif home directory:

JET: /lfs4/BMC/amb-verif/verif_repos/VxLegacyIngest/JET
HERA: /scratch2/BMC/amb-verif/verif_repos/VxLegacyIngest/HERA

I expect to have the permission issues resolved later this week.

**Comment by JeffHamiltonNOAA** [comment]
Permission issue has been resolved. This issue is now closed
