### ISSUE TITLE
Backfill RRFSE and HREF systems back to May 2022

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#476]
Chunhua has requested that I backfill RRFSE data to early May in our ensemble verification app. She sent me the location on the cloud where data is being stored, located here:

https://noaa-gsl-experimental-pds.s3.amazonaws.com/index.html#rrfs_b_ensemble/

Additionally, backfill the HREF system as well, for operational comparison

**Comment by JeffHamiltonNOAA** [comment]
The mechanism that I used in the past to pull data from an AWS instance appears to only be available to machines in the GSL environment, not on HPC. I'll need to see what mechanism exists to do this there

**Comment by JeffHamiltonNOAA** [comment]
With Jet being unstable, I decided to experiment with Globus to pull from the S3 bucket where RRFSE data is archived. I've had success to a point (the transfer nodes on Jet are still having trouble), but learned some lessons along the way. Most importantly, I cannot run Globus as amb-verif and I cannot login via the URL provided through the VPN (likely firewall issues per the Jet SAs). Not sure what this means for automated runs, but I'll experiment with that once Jet recovers

**Comment by JeffHamiltonNOAA** [comment]
I've successfully pulled back 5 days of RRFSE data using Globus from AWS to Jet and have run our ensemble scripts on the data, albeit with some difficulty with Jet instability. Once the system is back up, I will continue

**Comment by bonnystrong** [comment]
Matt: Matt Wandishin
We should ask whether the RRFS-E backfill is necessary. With all of the changes going on, it may not be relevant to the modelers.

**Comment by JeffHamiltonNOAA** [comment]
Closing this issue as it is no longer relevant with the move to MPAS
