### ISSUE TITLE
Create normalized UA database schema

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#496]
Molly has discovered the large inconsistencies in our UA database table schema, specifically in ruc_ua_sums2, is causing problems with her work trying to remove all statistical calculations from the MATS queries. Work on creating a new ruc_ua_sums3 in our database and adjust our ingest and schema design to be consistent across all models.

**Comment by JeffHamiltonNOAA** [comment]
I have created a ruc_ua_sums3 in our database and am looking at all of the different schemas available in the old area for inclusion in the new template. I'm finding widespread inconsistencies as I move forward and am noticing how many exceptions currently exist in the legacy ingest as well. This will all need to change and be kept in the forefront when designing the new ingest UA app.

**Comment by JeffHamiltonNOAA** [comment]
I believe I have tracked down the maximum number of columns to include in this new schema, removing inconsistencies across all tables. Setting up a template to reflect this and then designing queries to delicately move data from the old to new. Additionally, hard-coded exceptions will be removed from the ingest scripts to handle these inconsistencies as well.

**Comment by bonnystrong** [comment]
Jeff, I don't think you mean "normalize" in the sense of a 1st-normal-form database, do you?  I was a little confused.

**Comment by JeffHamiltonNOAA** [comment]
Hi Bonny, no, I do not. Sorry for the confusion. A better detailed description would be schema standardization across all tables

**Comment by JeffHamiltonNOAA** [comment]
Template table is in place. Creating parallel real time ingest scripts to look at this new table format and removing hard coded exceptions in order to handle various schemas. These exceptions are everywhere, but once completed, I will set up parallel processing for all models being verified in real time, then transfer over stats from the old ruc_ua_sums2 database

**Comment by JeffHamiltonNOAA** [comment]
Finalizing parallel ingest and will begin testing this afternoon

**Comment by JeffHamiltonNOAA** [comment]
Parallel ingest is now running in real time. I needed to correct a few things in the old model-obs pairs database and also removed jobs that were running for models no longer producing output in both the old and new versions, but everything is running in a stable manner with the new schema. I'll pass this information along to Molly for her continued testing and close this issue, opening another for final transfer of legacy data while the parallel runs to ensure consistency.
