### ISSUE TITLE
Add RRFS-based RTMA to our verification suite

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#510]
Per Craig, the RTMA team would like to add the RRFS-based RTMA-B to our verification suites (UA, surface, ceiling, visibility). Data paths are as follows on Jet:

/home/rtrr/rtma_dev1/RTMA_CONUS.{YYYYMMDD}/{HH}

**Comment by mollybsmith-noaa** [comment]
This RTMA has been added to our surface, ceiling, visibility, and upper air workflows. Statistics are currently viewable in MATS.
