### ISSUE TITLE
Add RRFS_AK retro capability

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#513]
Hongli has asked about adding an Alaska RRFS capability to our retro scripts. Work to incorporate this into each verification type

**Comment by mollybsmith-noaa** [comment]
Hongli needs this before Jeff is back so I am working on it now.

**Comment by mollybsmith-noaa** [comment]
Thanks to Jeff this is now done in our UA verification.

**Comment by JeffHamiltonNOAA** [comment]
I have completed the upgrades on Jet to the ceiling and surface verification. Visibility is still giving me some trouble, but as soon as I have that sorted out, I'll move this capability over to Hera

**Comment by JeffHamiltonNOAA** [comment]
RRFS Alaska retro capability is now available on Jet and Hera for RAOB, surface, ceiling, and visibility verification. This issue can be closed
