### ISSUE TITLE
Add data purging to RRFS models in grid-to-grid verification

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxLegacyIngest#516]
Our HRRR- and RAP-based models have automatic data purging in our grid-to-grid verification, but the RRFS-based models do not, and this is causing /lfs1 to fill up every couple of months. We need to purge the following data with rocoto so we don't have to do it manually:

cref
----
RRFSE
RRFS_A
RRFS_B
RRFS_NA_3KM_DEV1
RTMA_DEV1
The three MPAS models

etp
----
RRFS_A
RRFS_B
RTMA_3D

vil
----
NAM_NEST
NSSL
RTMA_3D

precip
----
RRFS_A
RRFS_B
RRFS_NA_3KM_DEV1
The three MPAS models

**Comment by mollybsmith-noaa** [comment]
Co-assigning this issue to Jeff because either of us might get to it first.

**Comment by mollybsmith-noaa** [comment]
I am manually purging January's data from these directories today, as I haven't had time to set up a purge script yet.

**Comment by JeffHamiltonNOAA** [comment]
Moving this to a higher priority due to the Jet and Hera file systems filling up. This data only accounts for part of the problem, but is the easiest thing to modify from my end.

**Comment by JeffHamiltonNOAA** [comment]
This has been done for RRFS A and B. I'll add the three MPAS models as well, and then this issue will be completed.

**Comment by bonnystrong** [comment]
Will also do MPAS models.

**Comment by mollybsmith-noaa** [comment]
We really need NAM_NEST, NSSL, RRFSE, RRFS_NA_3KM_DEV1, RTMA_3D, and RTMA_DEV1 as well, they just brought our quota to 105%.

**Comment by mollybsmith-noaa** [comment]
Scratch RTMA_3D, that one is defunct.

**Comment by mollybsmith-noaa** [comment]
precip_1hr is not purging at all

**Comment by JeffHamiltonNOAA** [comment]
All models listed, along with 1 hr precip, are now properly purging. This issue can be closed
