### ISSUE TITLE
RRFS_NA_3km_dev1 verification on the full RRFS domain is not working correctly

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxLegacyIngest#520]
Full verification on the RRFS domain appears to not be fully set up yet. It looks like Jeff may have finished it for upper air, but none of the other grid-to-obs workflows is operating correctly. Surface runs without errors but produces dramatically wrong values, while ceiling and visibility don't run at all. I'm assigning both Jeff and myself to this issue, there's no way I can get it done before he comes back *and* help finish the scorecard.

**Comment by bonnystrong** [comment]
Following this in #508 so don't need another issue
