### ISSUE TITLE
Update handling of partial/incomplete files in legacy system

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#523]
Typically in the legacy system, when we come across partial and/or incomplete files, we throw an error and exit the script/executable that encounters it. This was done due to the fact that it was a rare occurrence with all types of model output (retro, experimental, and operational) and was worth checking. This does not appear to be the case for whatever reason with the various flavors of RRFS, especially over the past few weeks. Obviously, tuning is ongoing and the transfers from WCOSS are not as mature as the operational grids, so I'll need to update the handling of these files to just throw a flag saying it is incomplete and move onto the next file. This is not ideal, but if left alone we will continually get an avalanche of error emails and verification will not be processed for longer lead times valid as the same point as the incomplete files.

**Comment by JeffHamiltonNOAA** [comment]
Ming is working on this as it appears to be a WCOSS problem and was happening with accelerating frequency that I did not want to change our code to accommodate a bug upstream. I'll leave this open for now, but it may not be relevant moving forward

**Comment by bonnystrong** [comment]
No longer seeing any problems so closing this.
