### ISSUE TITLE
Add NSSL MPAS to verification suite

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#529]
David Dowell has asked for three versions of the NSSL MPAS experimental model to be added to our verification suite, specifically reflectivity, precipitation, surface, and RAOB UA. The file naming convention and locations are as follows:

MPAS_HT_NSSL
~role.rtrr/mpas_ht_nssl/YYYYMMDDHH_HT/upp/MPAS-A_YYYYMMDDHH_HTfFF.grib2

MPAS_HN_NSSL
~role.rtrr/mpas_hn_nssl/YYYYMMDDHH_HN/upp/MPAS-A_YYYYMMDDHH_HNfFF.grib2

MPAS_RT_NSSL
~role.rtrr/mpas_rt_nssl/YYYYMMDDHH_RT/upp/MPAS-A_YYYYMMDDHH_RTfFF.grib2 

I spoke with Curtis and Steve on prioritization and they said it would be nice to have it up before the spring experiment (May) in order to have stats for scientists to examine compared to operational HRRR and experimental RRFS.

**Comment by mollybsmith-noaa** [comment]
I've added these models to our surface, ceiling, visibility, cref, and precip verifications. David says the cref and precip ones don't seem to be populating in the database, so I'll look into why as soon as Jet is back up.

**Comment by mollybsmith-noaa** [comment]
I didn't update this issue before I left, but I did get the cref and percip verifications working that week.
