### ISSUE TITLE
Revert all Verification Slurm jobs back to original partitions

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#531]
PPA is not going to stick around after April 7, and we will need to revert our jobs back to the original Jet partitions in order to keep them going. Jeff will handle grid-to-obs and reflectivity/precip, while Molly will handle grid-to-grid (METplus)

**Comment by JeffHamiltonNOAA** [comment]
I have switched all grid-to-obs and non-METplus scripts running in real time on Jet back to the normal Jet paritions (xJet, vJet, etc.) and the normal service nodes.

**Comment by mollybsmith-noaa** [comment]
I have switched all METplus verification back (grid-to-grid, TC, MODE, and ensemble), so I am closing this issue.
