### ISSUE TITLE
Enable 3km NA RRFS A

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#544]
Dave has indicated that RRFS A will soon be upgraded to the full 3km North American domain. Once this happens, test out our projection upgrades across all verification types to ensure proper functionality with a real time model.

**Comment by bonnystrong** [comment]
Jeff is working on incorporating this into workflow.  Has some complexities that need to be addressed as he progresses.

**Comment by JeffHamiltonNOAA** [comment]
All apps are now running real time with RRFS A NA. This issue can be closed
