### ISSUE TITLE
MPAS surface verification bug

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#562]
Amanda discovered a bug in our surface verification of MPAS_RT_NSSL. This particular version is on a smaller domain than the HRRR grid, but uses fill values to output on that grid. Our system is not properly handling the fill value (though code exists to do this). Investigate and correct, backfill where possible/necessary

**Comment by natalieb-noaa** [comment]
Previous sums have been deleted, closing issue.
