### ISSUE TITLE
StageIV 6 hour precip accumulation bug

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#563]
While looking into issues for Ruifang, I've found an error in our code for 12 and 24 hour accumulations leading to valid time confusion. Fortunately, in revealing it, I've realized that what I told her before was incorrect. The valid time inside the combined interpolated Stage IV netcdf files is incorrectly assigned to be 6 hours past the accumulation period. So the files for the 24 and 12 hour accumulations are correct and correspond to the date directory they are in rather than the valid time in the file metadata. I've corrected the mislabeling moving forward, but unfortunately the archived data will still have it in place for retros for some time.

However, that also means that what I previously told her was incorrect about the 6-hour files that have not been added together. Those valid times were labeled correctly and the incorrect file was referenced during verification. Even worse, this bug has likely been in place for some time as this part of the code hasn't been touched in over 8 years. I'm going through our sub-24hour verification code to make corrections where necessary and am going to discuss what to do with the older statistics for 6-hour accumulation forecasts with our team.

**Comment by JeffHamiltonNOAA** [comment]
I've corrected this issue in our code on Jet/Hera. I'll hold off on removing everything from before in order to see the magnitude of the change on our statistics. If need be, I'll create another issue for that

**Comment by bonnystrong** [comment]
Will not reprocess older data, at least for now.  Modelers want to keep old data to see the change.
