### ISSUE TITLE
retro support for Haidao

### ISSUE THREAD

**Issue by natalieb-noaa** [NOAA-GSL/VxLegacyIngest#582]
From Haidao:

surface verification:
_It looks like recently I can not get surface verification working for my retro runs (NA 13km RRFS), 
These are the command I used for my retro runs:

    274 #15 0,12 * * * $HOME/ruc_madis_surface/beta/retro.tcsh RRFS_NA_13kmret_April2023_v050_v14 1681862400 1682726400  > /dev/null 2>&1
    275 00 0,6,12,18 * * * $HOME/ruc_madis_surface/beta/retro.tcsh RRFS_NA_13kmret_April2023_v050_v15 1681862400 1682726400  > /dev/null 2>&1

but it looks like I did not see them in the MATS.

Could you please check it? _

ceiling verification:
_It looks like I can not get ceiling verification working for my retro runs (NA 13km RRFS), 
These are the command I used for my retro runs:
#20  0,12 * * * $HOME/ceiling/retro_driver.tcsh  RRFS_NA_13kmret_April2023_v050_v14 1681862400 1682726400   > /dev/null 2>&1
    305 00  0,6,12,18 * * * $HOME/ceiling/retro_driver.tcsh  RRFS_NA_13kmret_April2023_v050_v15 1681862400 1682726400   > /dev/null 2>&1
    
but it looks like I did not see them in the MATS.

Could you please check it? _

**Comment by JeffHamiltonNOAA** [comment]
This looks to be a combination of two issues. First, the old file convention is being used for RRFS NA 13km (there wasn't an example of what the new one should look like until Haidao provided this case) and second, the grid specifications for the NA 13km domain are still set to the original, RAP like grid. These will need to be changed in the executables (rotated lat-lon has to be hard coded in the legacy system, unfortunately)

**Comment by JeffHamiltonNOAA** [comment]
I've updated the naming convention to look for Haidao's retro and updated the projection transformation to properly use the 13km grid parameters with the new method. This issue has been resolved
