### ISSUE TITLE
Add WFIP3 capabilities to our system

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#584]
Joe and Dave have asked for a new verification to be put in place for the WFIP3 project. Joe has experimental runs in place on Jet and has asked for the coarser grid to be put into our surface, ceiling/visibility, upper-air (sonde and aircraft), and precip applications. Additionally, in order to make this useable, he has asked for a new domain to be used in our system with the following boundaries:

Upper Left Corner: Latitude = 46.86, Longitude = -80.59
Upper Right Corner: Latitude = 46.86, Longitude = -61.01
Lower Left Corner: Latitude = 33.66, Longitude = -78.83
Lower Right Corner: Latitude = 33.66, Longitude = -62.77

Create this domain, then add the experimental runs from Jet:

/lfs1/BMC/rtwbl/WFIP3/outputs/upp_out

**Comment by natalieb-noaa** [comment]
this is done, closing.
