### ISSUE TITLE
Recompile executables for Rocky8 OS

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#586]
With the ongoing transition on Jet/Hera to Rocky8, we will need to recompile all executables/libraries on both systems in order to avoid issues.

**Comment by mollybsmith-noaa** [comment]
Unassigning myself because I've created a separate issue for the METplus stuff.

**Comment by JeffHamiltonNOAA** [comment]
I have recompiled everything on Jet and Hera that runs in real time, and am working through the retrospective scripts on both machines as well

**Comment by JeffHamiltonNOAA** [comment]
This issue has been completed for realtime and retrospective cases, except for unique areas where large scale design modifications need to be made (e.g. legacy aircraft). This issue can be closed
