### ISSUE TITLE
Overhaul aircraft retro verification on Hera

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxLegacyIngest#592]
Amanda has asked for RRFS (CONUS for now) aircraft retro verification on Hera. Looking at our scripts, we have placeholders for this capability there but the entire pearl/Fortran code base is in need of attention. Work to upgrade both aspects and add the NA 3km code as well

**Comment by mollybsmith-noaa** [comment]
THis is done.
